locales:
  en:
    name: Réunion Creole French Keyboards
    description: >-
      Mobile OS keyboards for the Réunion Creole French language from the Divvun
      group at UiT.
  nb:
    name: Réunion Creole French tastatur
    description: Mobiltastatur for Réunion Creole French fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga árktalaš universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga árktalaš universitehta
