template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 22
template_sha = "bcb8b286fa17624dfca431a06ac6c92581ec25ba"

[replacements]
__UND2C__ = "rcf"
__UNDEFINED__ = "Réunion Creole French"
__UND__ = "rcf"
